# Generated by Django 4.2.4 on 2023-08-19 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_user_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.number'),
        ),
    ]
