# Generated by Django 4.2.4 on 2023-08-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_type_alter_challenge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.major'),
        ),
    ]
