# Generated by Django 4.2.4 on 2023-08-21 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_category_remove_challenge_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_challenge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
