# Generated by Django 4.2.4 on 2023-08-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_challenge_like_users_alter_challenge_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(),
        ),
    ]
