# Generated by Django 4.2.4 on 2023-08-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_alter_challenge_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
